FROM alpine:latest
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update && apk add --no-cache maven tomcat9
COPY pom.xml /usr/local/hello/pom.xml
COPY src /usr/local/hello/src
WORKDIR /usr/local/hello
RUN mvn package
WORKDIR /hello/boxfuse-sample-java-war-hello/target
RUN mv hello-1.0.war /var/lib/tomcat9/webapps
EXPOSE 8080
CMD ["/usr/share/tomcat9/bin/catalina.sh", "run"]
